vich_uploader:
    db_driver: orm

    mappings:
        gallery_images:
            uri_prefix: /asset/img/gallery
            upload_destination: "%kernel.project_dir%/public/asset/img/gallery"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
